### ISSUE TITLE
Zenoh currently only seems to support Micro URI

### ISSUE THREAD

**Issue by ALPayne18** [eclipse-uprotocol/up-client-zenoh-cpp#44]
When I try to use a URI of the long form to the zenho API (example
https://github.com/eclipse-uprotocol/up-client-zenoh-cpp/blob/3c78b0503ae40d534471d867b9e07ea006d31abb/lib/include/up-client-zenoh-cpp/rpc/zenohRpcClient.h#L53C1-L53C104 ), the API call fails. Looking at the code it seems that only Micro URI are supported. 

```
std::string toZenohKeyString(const uprotocol::v1::UUri &u_uri) {
    constexpr std::string_view remote_prefix{"upr"};
    constexpr std::string_view local_prefix{"upl"};
    constexpr std::string_view separator{"/"};
    constexpr std::string_view wildcard_suffix{"**"};

    using Serializer = uprotocol::uri::MicroUriSerializer;
```
I feel that the zenho API should support both Micro or Long form URI per the up-spec (https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#long-uris).

This issue is also related to this issue (https://github.com/eclipse-uprotocol/up-cpp/issues/102) on the MicroSerializer. Because only micro URI is supported, none of the uSubscription URI can be accessed via the zenho cpp API.

**Comment by PLeVasseur** [comment]
Hi @ALPayne18 --

Some background:
* In 1.5.7 we have Micro and Long form UUris.
  * [`UTransport::send()`](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#21-send) and [`UTransport::registerListener()`](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#22-registerlistener) are written up such that the UUris present **MUST** satisfy `isMicroForm()` while being a Resolved UUri (i.e. with both strings and numeric values) is a **SHOULD**.
* In 1.5.8 we will no longer have Micro, Short, Long form distinctions: simply [UUri](https://github.com/eclipse-uprotocol/up-spec/blob/19bec77b3c3222def74604dbe5f5d0af2afb9ae1/up-core-api/uprotocol/uri.proto#L37)
  * Can you sanity check me here @stevenhartley? I've not been following this as closely as I should.

> This issue is also related to this issue (https://github.com/eclipse-uprotocol/up-cpp/issues/102) on the MicroSerializer. Because only micro URI is supported, none of the uSubscription URI can be accessed via the zenho cpp API.

OK, let's pick this issue up over there.

**Comment by ALPayne18** [comment]
> In 1.5.7 we have Micro and Long form UUris.
> * [`UTransport::send()`](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#21-send) and [`UTransport::registerListener()`](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#22-registerlistener) are written up such that the UUris present **MUST** satisfy `isMicroForm()` while being a Resolved UUri (i.e. with both strings and numeric values i.e. being _both_ Micro and Long form) is a **SHOULD**.

Hi @PLeVasseur , I was not aware of this restriction and change to the API. I was just looking at the header comments and it isn't clear there that the isMicroForm() must return true. I will make sure I check out the up-spec. That is certainly more verbose. I am okay if you want to close this issue.

**Comment by PLeVasseur** [comment]
Yes, it became fairly complicated to keep track of multiple UUri formats.

Should become simpler in 1.5.8.

I'm unable to close the issue as I'm not a committer, but you should be able to as the opener of the issue.

**Comment by ALPayne18** [comment]
Thanks for the feedback.
