### ISSUE TITLE
zenoh uTransport instance issue

### ISSUE THREAD

**Issue by pranavishere2** [eclipse-uprotocol/up-client-zenoh-cpp#47]
We are trying to run uStreamer in a open source and encountered issue specific to rpc usecase.

open source repo version used:
**up-cpp : v0.1.2-dev
up-client-zenoh-cpp: v0.1.4-dev
up-zenoh-example-cpp - v0.1.0-dev**

It looks like zenoh uTransport instance is changed to accept uAuthority and uEntity. 
For example:
std::shared_ptr<UpZenohClient> transport = UpZenohClient::instance( uprotocol::uri::BuildUAuthority().setName("uE3").build(),
 uprotocol::uri::BuildUEntity().setName("uE3").setMajorVersion(1).setId(300).build());

We cannot initialize it without providing any parameters as it causes segmentation fault saying that transport is a nullptr. If we provide UAuthority and UEntity then it fixes segmentation fault but when we use invokeMethod to send custom uMessage then it overrides the default source entity id which was used at the time of creating transport object.  We dont want to override uMessage uentity and that is the issue.

Is there anyway to initialize utransport without providing UAuthority and UEntity? OR if there is any better option then please suggest.

**Comment by stevenhartley** [comment]
uStreamer should not be using invokemethod() (L2 APIs) but only uTransport. This will become more evident when we conclude the 1.5.8 release shortly.

**Comment by pranavishere2** [comment]
Thank you for response. 

Are we going to use send API instead of invokeMethod in 1.5.8 ? 
Even though if we do not use invokeMethod in 1.5.8, I am curious to know how that is going to solve the original problem. Does 1.5.8 is going to provide way to initialize utransport instance without providing uAuthority and uEntity? I just want to make sure that attribute source entity id of "uMessage" passed via send method will not be overridden.

**Comment by stevenhartley** [comment]
Hi @pranavishere2 we need the authority for the transport in the streamer but all that you are doing is setting up forwarding rules to redirect messages from one transport to the next and vice versa. Lets setup a discussion on Streamer with Peter.

**Comment by pranavishere2** [comment]
We can close this issue as this is being taken care from uStreamer end and we are not going to use invoke method in 1_5_8 anyway.
